### ISSUE TITLE
Finalizar o doc de Arquitetura de Software

### ISSUE THREAD

**Issue by leohssjr** [unb-mds/2024-2-ChamaControl#15]
Fazer as alterações necessárias no doc/estudos/coelhos/arquitetura.md com a explicação sobre Arquitetura de Software, além de incluir links que foram utilizados para estudos.

**Comment by Guga301104** [comment]
**Links do estudo:**
<br><https://martinfowler.com/architecture/>
<br><https://www.spaceotechnologies.com/blog/front-end-frameworks-comparison/>
<br><https://www.couchbase.com/blog/backend-languages/>
