### ISSUE TITLE
Subir a versão inicial da GitPage do projeto com o mkdocs

### ISSUE THREAD

**Issue by Arturhk05** [unb-mds/2024-2-ChamaControl#19]
## Subir a versão inicial da GitPage do projeto com o mkdocs

**Descrição**
Estudar o funcionamento das `GitHub Pages` e entender como a ferramenta `mkdocs` funciona.

**Escopo**
Documentação

**Tópicos para a conclusão da tarefa**

- [x] Estudar o mkdocs;
- [x] Implementa-lo no projeto;
- [x] Criar página inicial do projeto;
- [x] Fazer deploy pela GitHub Pages;

**Comment by Edumorais08** [comment]
https://unb-mds.github.io/2024-2-InfraTranDF/
