### ISSUE TITLE
Prototipação do front-end no figma

### ISSUE THREAD

**Issue by Arturhk05** [unb-mds/2024-2-ChamaControl#23]
## Prototipação do front-end no figma.

**Descrição**
Essa tarefa tem como objetivo fazer um protótipo de como o será a página do site.

**Escopo**
Documentação front-end.

**Tópicos para a conclusão da tarefa**

- [x] Estudo básico sobre figma;
- [x] Criar a página figma e compartilhar o link;
- [x] Prototipar a página do site;

**Comment by Arturhk05** [comment]
Essa tarefa foi passada para a próxima semana.

**Comment by fbressa** [comment]
Protótipo do [figma:] (https://www.figma.com/design/mPqnz5g1fNN7PVtIgwt0ln/Queimadas-UnB?node-id=0-1&node-type=canvas&t=Q7LQPgX8Bv7EsQ53-0)
