### ISSUE TITLE
Criar WireFrame InfraTranDF

### ISSUE THREAD

**Issue by leohssjr** [unb-mds/2024-2-ChamaControl#24]
## Criação WireFrame InfraTranDF

**Descrição**
Criar uma primeira apresentação do wireframe do projeto para ter uma representação simplificada das principais telas e fluxos. Com o wireframe poderemos criar um protótipo da aplicação

**Comment by Arturhk05** [comment]
Devido a mudança do tema do projeto essa issue foi descontinuada.
