### ISSUE TITLE
Coelho(font-end): estudo sobre o básico do react

### ISSUE THREAD

**Issue by Arturhk05** [unb-mds/2024-2-ChamaControl#27]
## React

**O que é?**
Framework de front-end feito em javascript.

**Como funciona?**
Descreva brevemente o funcionamento do conceito ou tecnologia.

**Quem será o coelho?**
@leohssjr

**Tópicos a serem estudados**

- [x] Estudar conceitos básicos de react;
- [x] Como criar um projeto react;

**Link do estudo**
Defina o link da página onde é possível encontrar o estudo.

**Comment by leohssjr** [comment]
Estudei conceitos sobre react e apliquei em um primeiro protótipo para a aplicação web, irei criar um documento que irá conter os principais pontos de react

![image](https://github.com/user-attachments/assets/e544d18d-ac5f-4924-bc83-80aa8a4d6aa5)
![image](https://github.com/user-attachments/assets/18944667-4d9a-4316-8ea6-23f4dc0d547a)
![image](https://github.com/user-attachments/assets/03350a9a-4b01-4fe8-82c3-d5294494b24e)
